import { Knex } from 'knex';
import bcrypt from 'bcryptjs';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('users').del();

  // Hash passwords
  const passwordHash = await bcrypt.hash('password123', 10);

  // Inserts seed entries - No IDs or UUIDs (auto-generated by PostgreSQL)
  await knex('users').insert([
    {
      email: 'admin@movigo.com',
      name: 'Admin Principal',
      password_hash: passwordHash,
      status: 'ACTIVE',
      is_active: true,
    },
    {
      email: 'superadmin@movigo.com',
      name: 'Super Administrador',
      password_hash: passwordHash,
      status: 'ACTIVE',
      is_active: true,
    },
    {
      email: 'manager@movigo.com',
      name: 'Gerente General',
      password_hash: passwordHash,
      status: 'ACTIVE',
      is_active: true,
    },
  ]);
}
